### ISSUE TITLE
fails to install dependencies with yarn 

### ISSUE THREAD

**Issue by threepointone** [reasonml/rehydrate#23]
fresh git clone, running `yarn` gives this 
```
➜  rehydrate git:(master) yarn
yarn install v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: pull
Directory: /Users/threepointone/.yarn-cache/.tmp/baf9413ad449f940390553af573f88c0
Output:
warning: no common commits
From git://github.com/npm-opam/easy-format
 + 1b3ab29...8bce8fb master     -> origin/master  (forced update)
 + 6d7cda1...8bce8fb latest     -> origin/latest  (forced update)
fatal: refusing to merge unrelated histories
    at SpawnError (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/lib/errors.js:18:1)
    at ChildProcess.proc.on.code (/usr/local/Cellar/yarn/0.15.1/libexec/lib/node_modules/yarn/lib/util/child.js:107:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

```

worked fine with `npm install`

**Comment by chenglou** [comment]
cc @yunxing

**Comment by yunxing** [comment]
@threepointone 

Try remove /Users/threepointone/.yarn-cache.

Also I think this is fixed in the latest version of yarn (0.18.1).

**Comment by jdhorwitz** [comment]
Confirmed that this doesn't appear to be an issue any longer.  Verified on yarn (0.24.6)

**Comment by chenglou** [comment]
Thanks for verifying!

**Comment by asaphaaning** [comment]
Still an issue in yarn 1.9.4.

I deleted yarn.lock and it happened as I pull private repos defined in package.json.

yarn cache clean fixed the issue.

**Comment by kuworking** [comment]
For me `yarn cache clean` also worked, deleting `yarn.lock` o a `yarn-cache` folder (the only one I could find) didn't work

Yarn 1.17.3

**Comment by chenglou** [comment]
@kuworking wrong repo. New ReasonReact is at https://github.com/reasonml/reason-react
